In [17]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn import linear_model
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree 
from sklearn.metrics import mean_squared_error
from sklearn import tree 
from sklearn.model_selection import train_test_split

#### **Load Data**

In [18]:
df = pd.read_csv("data/Housing.csv")

In [19]:
df.head(2)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished

#### **Encoding**

In [20]:
df_copy = df # making a copy of the original data

In [21]:
df_copy =  pd.get_dummies(df_copy, columns=['furnishingstatus'], drop_first=True)

In [22]:
bin_cat_columns =[
    'mainroad',	'guestroom',	'basement',	'hotwaterheating',	'airconditioning',	'prefarea'
] 

for col in bin_cat_columns:
    df_copy[col] = df_copy[col].map({'yes':1, 'no':0})

In [23]:
df_copy.head(1)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,False,False

#### **SPlit data into independent and dependent(outcome)**

In [24]:
df_copy.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus_semi-furnished',
       'furnishingstatus_unfurnished'],
      dtype='str')

In [25]:
X = df_copy.drop("price", axis=1)
y = df_copy["price"]

In [31]:
X.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,7420,4,2,3,1,0,0,0,1,2,1,False,False
1,8960,4,4,4,1,0,0,0,1,3,0,False,False
2,9960,3,2,2,1,0,1,0,0,2,1,True,False
3,7500,4,2,2,1,0,1,0,1,3,1,False,False
4,7420,4,1,2,1,1,1,0,1,2,0,False,False

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
y_train   = pd.DataFrame(y_train, columns=['price'])

In [39]:
X_train.columns

Index(['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom',
       'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea',
       'furnishingstatus_semi-furnished', 'furnishingstatus_unfurnished'],
      dtype='str')

In [40]:
X_test.columns

Index(['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom',
       'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea',
       'furnishingstatus_semi-furnished', 'furnishingstatus_unfurnished'],
      dtype='str')

#### **Train model**

In [37]:
type(y_test)
y_test = pd.DataFrame(y_test, columns=['price'])

In [38]:
model = tree.DecisionTreeRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(y_test)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- price
Feature names seen at fit time, yet now missing:
- airconditioning
- area
- basement
- bathrooms
- bedrooms
- ...